# TCL File Generated by Component Editor 13.0sp1
# Fri Nov 15 13:17:14 EST 2013
# DO NOT MODIFY


# 
# CAMERA_IF "CAMERA_IF" v1.0
#  2013.11.15.13:17:14
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module CAMERA_IF
# 
set_module_property DESCRIPTION ""
set_module_property NAME CAMERA_IF
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Terasic Technologies Inc."
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME CAMERA_IF
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL CAMERA_IF
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file CAMERA_IF.v VERILOG PATH CAMERA_IF.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point s1_clock
# 
add_interface s1_clock clock end
set_interface_property s1_clock clockRate 0
set_interface_property s1_clock ENABLED true
set_interface_property s1_clock EXPORT_OF ""
set_interface_property s1_clock PORT_NAME_MAP ""
set_interface_property s1_clock SVD_ADDRESS_GROUP ""

add_interface_port s1_clock avs_s1_clk clk Input 1


# 
# connection point s1_clock_reset
# 
add_interface s1_clock_reset reset end
set_interface_property s1_clock_reset associatedClock s1_clock
set_interface_property s1_clock_reset synchronousEdges DEASSERT
set_interface_property s1_clock_reset ENABLED true
set_interface_property s1_clock_reset EXPORT_OF ""
set_interface_property s1_clock_reset PORT_NAME_MAP ""
set_interface_property s1_clock_reset SVD_ADDRESS_GROUP ""

add_interface_port s1_clock_reset avs_s1_reset reset Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressAlignment NATIVE
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock s1_clock
set_interface_property s1 associatedReset s1_clock_reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitStates 0
set_interface_property s1 readWaitTime 0
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_s1_address address Input 2
add_interface_port s1 avs_s1_readdata readdata Output 32
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_write write Input 1
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point s1_export
# 
add_interface s1_export conduit end
set_interface_property s1_export associatedClock ""
set_interface_property s1_export associatedReset ""
set_interface_property s1_export ENABLED true
set_interface_property s1_export EXPORT_OF ""
set_interface_property s1_export PORT_NAME_MAP ""
set_interface_property s1_export SVD_ADDRESS_GROUP ""

add_interface_port s1_export avs_s1_export_clk export Output 1
add_interface_port s1_export avs_s1_export_address export Output 2
add_interface_port s1_export avs_s1_export_readdata export Input 32
add_interface_port s1_export avs_s1_export_read export Output 1
add_interface_port s1_export avs_s1_export_writedata export Output 32
add_interface_port s1_export avs_s1_export_write export Output 1
add_interface_port s1_export avs_s1_export_reset export Output 1

